name: Test and Release

on:
  push:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Install Dependencies
        run: poetry install
      - name: Test with PyTest
        run: poetry run pytest --cov=pyboinc --cov-report=xml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml

  Release:
    runs-on: ubuntu-latest
    needs: Test
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.2
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          branch: main
          patchList: fix,bugfix
          noVersionBumpBehavior: silent
          token: ${{ secrets.GH_TOKEN }}
      - name: Bump Poetry Version
        run: poetry version ${{ steps.semver.outputs.nextStrict }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Create ${{ steps.semver.outputs.next }} Release"
          tagging_message: ${{ steps.semver.outputs.next }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        if: ${{ steps.semver.outputs.next != null }}
        with:
          name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
          makeLatest: true
          generateReleaseNotes: true
          skipIfReleaseExists: true
